// <auto-generated />
using System;
using EventManager.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventManager.Domain.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventManager.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Identifier");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("e72e35ba-3d63-40ae-adf0-e45c5e393b05"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 476, DateTimeKind.Local).AddTicks(9180),
                            EndDate = new DateTime(2021, 9, 11, 0, 2, 22, 474, DateTimeKind.Local).AddTicks(9259),
                            EventDescription = " Feest-Hansen 's 72 rd/th Annual Conference at Indonesia, Legrosmouth - INVERSE MOBILE TOOLSET. ",
                            EventName = " Feest-Hansen 's 72 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 476, DateTimeKind.Local).AddTicks(9531),
                            StartDate = new DateTime(2021, 9, 10, 0, 2, 22, 474, DateTimeKind.Local).AddTicks(9259)
                        },
                        new
                        {
                            Identifier = new Guid("d858e300-143a-4adc-9054-81628754068a"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(1865),
                            EndDate = new DateTime(2021, 9, 17, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(1607),
                            EventDescription = " Ward-Wisoky 's 78 rd/th Annual Conference at Moldova, West Jamarcusbury - COMPATIBLE OBJECT-ORIENTED ARRAY. ",
                            EventName = " Ward-Wisoky 's 78 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(1867),
                            StartDate = new DateTime(2021, 9, 16, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(1607)
                        },
                        new
                        {
                            Identifier = new Guid("50eb9201-6431-449b-b81e-0275b810d00f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(6865),
                            EndDate = new DateTime(2021, 10, 7, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(6756),
                            EventDescription = " Wiegand Group 's 98 rd/th Annual Conference at Mali, Ivorychester - RE-ENGINEERED CONTENT-BASED INFRASTRUCTURE. ",
                            EventName = " Wiegand Group 's 98 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(6867),
                            StartDate = new DateTime(2021, 10, 6, 0, 2, 22, 479, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Identifier = new Guid("f3521f48-b27c-4438-abea-48439a1a7fd0"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(2476),
                            EndDate = new DateTime(2021, 8, 25, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(2362),
                            EventDescription = " Stehr, Schroeder and Hessel 's 55 rd/th Annual Conference at Liechtenstein, Cathrineton - OPEN-SOURCE SYSTEMIC WORKFORCE. ",
                            EventName = " Stehr, Schroeder and Hessel 's 55 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(2477),
                            StartDate = new DateTime(2021, 8, 24, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(2362)
                        },
                        new
                        {
                            Identifier = new Guid("64553b5c-1282-4455-a02f-627a6e9d0c45"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(5613),
                            EndDate = new DateTime(2021, 7, 4, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(5522),
                            EventDescription = " Luettgen-Harber 's 3 rd/th Annual Conference at Iraq, Tatyanaland - MANAGED GLOBAL METHODOLOGY. ",
                            EventName = " Luettgen-Harber 's 3 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(5614),
                            StartDate = new DateTime(2021, 7, 3, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(5522)
                        },
                        new
                        {
                            Identifier = new Guid("5bb6b163-4d0e-4ae6-8a6e-26572322b992"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(9714),
                            EndDate = new DateTime(2021, 9, 19, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(9635),
                            EventDescription = " Bruen, Larson and Purdy 's 80 rd/th Annual Conference at Australia, South Osvaldo - ASSIMILATED BIFURCATED HUB. ",
                            EventName = " Bruen, Larson and Purdy 's 80 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(9716),
                            StartDate = new DateTime(2021, 9, 18, 0, 2, 22, 480, DateTimeKind.Local).AddTicks(9635)
                        },
                        new
                        {
                            Identifier = new Guid("5a18c891-221e-46c9-8205-28d40454b980"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(2432),
                            EndDate = new DateTime(2021, 7, 6, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(2406),
                            EventDescription = " Brown-Welch 's 5 rd/th Annual Conference at Sudan, West Verla - BALANCED INTANGIBLE STRUCTURE. ",
                            EventName = " Brown-Welch 's 5 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(2433),
                            StartDate = new DateTime(2021, 7, 5, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(2406)
                        },
                        new
                        {
                            Identifier = new Guid("081b3162-590c-4b78-87d9-d3f4ca2175cf"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(4981),
                            EndDate = new DateTime(2021, 8, 9, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(4944),
                            EventDescription = " Morar LLC 's 39 rd/th Annual Conference at Azerbaijan, South Deborahberg - OPTIONAL MULTIMEDIA INSTALLATION. ",
                            EventName = " Morar LLC 's 39 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(4983),
                            StartDate = new DateTime(2021, 8, 8, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(4944)
                        },
                        new
                        {
                            Identifier = new Guid("d3711ca5-1d77-49a3-baf7-346865df1e17"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(6571),
                            EndDate = new DateTime(2021, 8, 5, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(6488),
                            EventDescription = " McGlynn-Lowe 's 35 rd/th Annual Conference at Burundi, Kozeyton - PROGRESSIVE EXPLICIT ALLIANCE. ",
                            EventName = " McGlynn-Lowe 's 35 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(6572),
                            StartDate = new DateTime(2021, 8, 4, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(6488)
                        },
                        new
                        {
                            Identifier = new Guid("98048893-7de9-426b-8e43-268f2a95338d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(8490),
                            EndDate = new DateTime(2021, 7, 19, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(8446),
                            EventDescription = " Wintheiser-Fay 's 18 rd/th Annual Conference at Nauru, Harveyberg - PRE-EMPTIVE DYNAMIC POLICY. ",
                            EventName = " Wintheiser-Fay 's 18 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(8492),
                            StartDate = new DateTime(2021, 7, 18, 0, 2, 22, 481, DateTimeKind.Local).AddTicks(8446)
                        },
                        new
                        {
                            Identifier = new Guid("f1315dcb-cf93-4d1e-a308-bdae11a49ffc"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(2667),
                            EndDate = new DateTime(2021, 9, 26, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(2459),
                            EventDescription = " Turner, Quigley and Emard 's 87 rd/th Annual Conference at Iraq, Port Leo - FOCUSED HYBRID WEBSITE. ",
                            EventName = " Turner, Quigley and Emard 's 87 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(2669),
                            StartDate = new DateTime(2021, 9, 25, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(2459)
                        },
                        new
                        {
                            Identifier = new Guid("2d0c45b6-0c54-4c42-8f24-6256c9eb7d9a"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(4484),
                            EndDate = new DateTime(2021, 8, 11, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(4454),
                            EventDescription = " Lindgren, Jaskolski and Schinner 's 41 rd/th Annual Conference at Pitcairn Islands, Marquardtmouth - TEAM-ORIENTED INTERMEDIATE INFO-MEDIARIES. ",
                            EventName = " Lindgren, Jaskolski and Schinner 's 41 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(4486),
                            StartDate = new DateTime(2021, 8, 10, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(4454)
                        },
                        new
                        {
                            Identifier = new Guid("d10df8fd-dd62-4dd9-849a-3650141cef33"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(9854),
                            EndDate = new DateTime(2021, 8, 31, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(9650),
                            EventDescription = " Hackett, Goldner and Bailey 's 61 rd/th Annual Conference at Antigua and Barbuda, Tobyfurt - MANAGED ASSYMETRIC PROCESS IMPROVEMENT. ",
                            EventName = " Hackett, Goldner and Bailey 's 61 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(9858),
                            StartDate = new DateTime(2021, 8, 30, 0, 2, 22, 482, DateTimeKind.Local).AddTicks(9650)
                        },
                        new
                        {
                            Identifier = new Guid("1981f470-bb5a-4f2c-b314-84994a6d7c71"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(3562),
                            EndDate = new DateTime(2021, 7, 27, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(3462),
                            EventDescription = " Breitenberg, Dietrich and Torphy 's 26 rd/th Annual Conference at Barbados, Kertzmannberg - SWITCHABLE RESPONSIVE SECURED LINE. ",
                            EventName = " Breitenberg, Dietrich and Torphy 's 26 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(3564),
                            StartDate = new DateTime(2021, 7, 26, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(3462)
                        },
                        new
                        {
                            Identifier = new Guid("04d4d065-b91f-4dfa-b943-ad30cd3d80bb"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(9292),
                            EndDate = new DateTime(2021, 8, 30, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(9168),
                            EventDescription = " Bogan, Brakus and Smitham 's 60 rd/th Annual Conference at Grenada, East Ransomfurt - PRE-EMPTIVE EMPOWERING DEFINITION. ",
                            EventName = " Bogan, Brakus and Smitham 's 60 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(9294),
                            StartDate = new DateTime(2021, 8, 29, 0, 2, 22, 483, DateTimeKind.Local).AddTicks(9168)
                        },
                        new
                        {
                            Identifier = new Guid("654e5925-4257-43a7-8a96-bbdc6f0df7fd"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(2346),
                            EndDate = new DateTime(2021, 7, 26, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(2201),
                            EventDescription = " Reilly, Kris and Koch 's 25 rd/th Annual Conference at New Caledonia, Kleintown - MULTI-LATERAL LOGISTICAL WORKFORCE. ",
                            EventName = " Reilly, Kris and Koch 's 25 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(2348),
                            StartDate = new DateTime(2021, 7, 25, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(2201)
                        },
                        new
                        {
                            Identifier = new Guid("5abaa9ef-0d87-4a44-91fd-0a97c043b8a7"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(5696),
                            EndDate = new DateTime(2021, 8, 19, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(5632),
                            EventDescription = " Howe-Will 's 49 rd/th Annual Conference at Lithuania, East Hilda - UPGRADABLE STATIC LEVERAGE. ",
                            EventName = " Howe-Will 's 49 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(5698),
                            StartDate = new DateTime(2021, 8, 18, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(5632)
                        },
                        new
                        {
                            Identifier = new Guid("d0435818-230b-4395-840b-6c6f70ab7148"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(8613),
                            EndDate = new DateTime(2021, 9, 12, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(8578),
                            EventDescription = " Pacocha-Kiehn 's 73 rd/th Annual Conference at Congo, Port Levi - POLARISED OBJECT-ORIENTED LEVERAGE. ",
                            EventName = " Pacocha-Kiehn 's 73 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(8615),
                            StartDate = new DateTime(2021, 9, 11, 0, 2, 22, 484, DateTimeKind.Local).AddTicks(8578)
                        },
                        new
                        {
                            Identifier = new Guid("f359bc30-58b5-46aa-8610-f2f7c36e0f9e"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(1100),
                            EndDate = new DateTime(2021, 8, 7, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(1079),
                            EventDescription = " Denesik-Veum 's 37 rd/th Annual Conference at Cambodia, Lilianmouth - SWITCHABLE SYSTEM-WORTHY PORTAL. ",
                            EventName = " Denesik-Veum 's 37 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(1101),
                            StartDate = new DateTime(2021, 8, 6, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(1079)
                        },
                        new
                        {
                            Identifier = new Guid("182f0fcc-7ce1-4fbc-b3fa-ab67f49bdb9f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(4744),
                            EndDate = new DateTime(2021, 8, 13, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(4652),
                            EventDescription = " Bruen, Torp and Blanda 's 43 rd/th Annual Conference at Antigua and Barbuda, North Caden - TOTAL OBJECT-ORIENTED ARRAY. ",
                            EventName = " Bruen, Torp and Blanda 's 43 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(4746),
                            StartDate = new DateTime(2021, 8, 12, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(4652)
                        },
                        new
                        {
                            Identifier = new Guid("208fa61c-bbbd-495e-8f75-88954afe3365"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(6971),
                            EndDate = new DateTime(2021, 7, 2, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(6927),
                            EventDescription = " Yundt, Rau and Hodkiewicz 's 1 rd/th Annual Conference at Switzerland, Zemlakhaven - PERSISTENT CLIENT-SERVER DATA-WAREHOUSE. ",
                            EventName = " Yundt, Rau and Hodkiewicz 's 1 rd/th Annual Conference",
                            EventTimezone = "Australia/Broken_Hill",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(6973),
                            StartDate = new DateTime(2021, 7, 1, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(6927)
                        },
                        new
                        {
                            Identifier = new Guid("fe45b800-9e9b-430f-a731-7aa8684e08d7"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(8512),
                            EndDate = new DateTime(2021, 7, 29, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(8478),
                            EventDescription = " Ernser Inc and Sons 's 28 rd/th Annual Conference at Russian Federation, Schambergertown - ADVANCED HOMOGENEOUS FRAME. ",
                            EventName = " Ernser Inc and Sons 's 28 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(8514),
                            StartDate = new DateTime(2021, 7, 28, 0, 2, 22, 485, DateTimeKind.Local).AddTicks(8478)
                        },
                        new
                        {
                            Identifier = new Guid("2f3b8091-53ad-47ed-885c-f42700be3396"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(2026),
                            EndDate = new DateTime(2021, 8, 24, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(1983),
                            EventDescription = " Johnston-Lynch 's 54 rd/th Annual Conference at Grenada, New Arely - PROGRESSIVE BIFURCATED SUPERSTRUCTURE. ",
                            EventName = " Johnston-Lynch 's 54 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(2027),
                            StartDate = new DateTime(2021, 8, 23, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(1983)
                        },
                        new
                        {
                            Identifier = new Guid("b6e10a0b-cc8f-4380-ad09-a1e352094762"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(4514),
                            EndDate = new DateTime(2021, 9, 20, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(4492),
                            EventDescription = " Abshire-Wunsch 's 81 rd/th Annual Conference at New Zealand, Brianneside - POLARISED REGIONAL PRICING STRUCTURE. ",
                            EventName = " Abshire-Wunsch 's 81 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(4515),
                            StartDate = new DateTime(2021, 9, 19, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(4492)
                        },
                        new
                        {
                            Identifier = new Guid("2f7059f9-cf19-487c-b734-bf61a0755fb9"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(6863),
                            EndDate = new DateTime(2021, 9, 18, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(6835),
                            EventDescription = " Crona Group 's 79 rd/th Annual Conference at Gabon, Port Gabriellestad - REDUCED STABLE ENCODING. ",
                            EventName = " Crona Group 's 79 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(6864),
                            StartDate = new DateTime(2021, 9, 17, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(6835)
                        },
                        new
                        {
                            Identifier = new Guid("703e5840-86ff-4999-920e-ce1b591e41a3"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(9505),
                            EndDate = new DateTime(2021, 8, 13, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(9482),
                            EventDescription = " Casper-Marvin 's 43 rd/th Annual Conference at Cocos (Keeling) Islands, Brielleburgh - PERSISTENT CONTENT-BASED DEFINITION. ",
                            EventName = " Casper-Marvin 's 43 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(9506),
                            StartDate = new DateTime(2021, 8, 12, 0, 2, 22, 486, DateTimeKind.Local).AddTicks(9482)
                        },
                        new
                        {
                            Identifier = new Guid("f9404323-5ab6-46e7-80de-ba7d22769d43"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(2130),
                            EndDate = new DateTime(2021, 9, 19, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(2107),
                            EventDescription = " Kub-Hayes 's 80 rd/th Annual Conference at Isle of Man, Lake Raul - FRONT-LINE REAL-TIME DATABASE. ",
                            EventName = " Kub-Hayes 's 80 rd/th Annual Conference",
                            EventTimezone = "Australia/Broken_Hill",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(2131),
                            StartDate = new DateTime(2021, 9, 18, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(2107)
                        },
                        new
                        {
                            Identifier = new Guid("1a21c5d5-c0b1-42e1-a3c8-c89fd726536d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(4949),
                            EndDate = new DateTime(2021, 9, 12, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(4892),
                            EventDescription = " Konopelski, Corwin and Ledner 's 73 rd/th Annual Conference at Albania, New Mervinfurt - DOWN-SIZED ZERO DEFECT ACCESS. ",
                            EventName = " Konopelski, Corwin and Ledner 's 73 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(4950),
                            StartDate = new DateTime(2021, 9, 11, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(4892)
                        },
                        new
                        {
                            Identifier = new Guid("2d9f28da-9a11-46db-b9ec-028272fb37c0"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(6224),
                            EndDate = new DateTime(2021, 8, 13, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(6186),
                            EventDescription = " Mraz Group 's 43 rd/th Annual Conference at Congo, Tillmantown - OBJECT-BASED SCALABLE INSTALLATION. ",
                            EventName = " Mraz Group 's 43 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(6225),
                            StartDate = new DateTime(2021, 8, 12, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(6186)
                        },
                        new
                        {
                            Identifier = new Guid("de1b3562-5272-4c2f-8aa9-94e8caeae735"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(8793),
                            EndDate = new DateTime(2021, 7, 21, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(8741),
                            EventDescription = " Bogisich-Krajcik 's 20 rd/th Annual Conference at Antigua and Barbuda, Efrainfort - STREAMLINED GLOBAL BUDGETARY MANAGEMENT. ",
                            EventName = " Bogisich-Krajcik 's 20 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(8795),
                            StartDate = new DateTime(2021, 7, 20, 0, 2, 22, 487, DateTimeKind.Local).AddTicks(8741)
                        },
                        new
                        {
                            Identifier = new Guid("6c49b388-42e1-4213-ada3-e161eeb545d3"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(1610),
                            EndDate = new DateTime(2021, 9, 15, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(1586),
                            EventDescription = " Dach-Nolan 's 76 rd/th Annual Conference at Burkina Faso, East Jessborough - CENTRALIZED UPWARD-TRENDING LOCAL AREA NETWORK. ",
                            EventName = " Dach-Nolan 's 76 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(1611),
                            StartDate = new DateTime(2021, 9, 14, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(1586)
                        },
                        new
                        {
                            Identifier = new Guid("71b6aaec-bae7-45ce-b1cc-09d15324c0f5"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(4195),
                            EndDate = new DateTime(2021, 8, 18, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(4168),
                            EventDescription = " Huels-Kautzer 's 48 rd/th Annual Conference at Poland, New Lynn - NETWORKED SECONDARY NEURAL-NET. ",
                            EventName = " Huels-Kautzer 's 48 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(4196),
                            StartDate = new DateTime(2021, 8, 17, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(4168)
                        },
                        new
                        {
                            Identifier = new Guid("1b846c9b-84b5-4f82-b367-762da50d3768"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(7150),
                            EndDate = new DateTime(2021, 7, 25, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(7090),
                            EventDescription = " Littel-Price 's 24 rd/th Annual Conference at Congo, Zolatown - PROACTIVE 6TH GENERATION METHODOLOGY. ",
                            EventName = " Littel-Price 's 24 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(7151),
                            StartDate = new DateTime(2021, 7, 24, 0, 2, 22, 488, DateTimeKind.Local).AddTicks(7090)
                        },
                        new
                        {
                            Identifier = new Guid("1aff197e-d921-4302-8510-cb3794a14e70"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(1914),
                            EndDate = new DateTime(2021, 7, 25, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(1480),
                            EventDescription = " Heathcote, Mraz and Abshire 's 24 rd/th Annual Conference at Paraguay, South Josephburgh - OPTIONAL ATTITUDE-ORIENTED SUPERSTRUCTURE. ",
                            EventName = " Heathcote, Mraz and Abshire 's 24 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(1918),
                            StartDate = new DateTime(2021, 7, 24, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(1480)
                        },
                        new
                        {
                            Identifier = new Guid("ff63dc31-63f5-418f-b151-cff344b9a3cf"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(3720),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(3614),
                            EventDescription = " Krajcik LLC 's 12 rd/th Annual Conference at Equatorial Guinea, Kuhicton - TRIPLE-BUFFERED LEADING EDGE MODEL. ",
                            EventName = " Krajcik LLC 's 12 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(3722),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(3614)
                        },
                        new
                        {
                            Identifier = new Guid("3ceb6a09-508f-4da2-a166-62de735df5dc"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(7712),
                            EndDate = new DateTime(2021, 7, 14, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(7375),
                            EventDescription = " Walter-Legros 's 13 rd/th Annual Conference at Marshall Islands, Port Mekhi - DIGITIZED STABLE SUPPORT. ",
                            EventName = " Walter-Legros 's 13 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(7715),
                            StartDate = new DateTime(2021, 7, 13, 0, 2, 22, 489, DateTimeKind.Local).AddTicks(7375)
                        },
                        new
                        {
                            Identifier = new Guid("71c5b945-5ca9-48ae-a318-2ccf2e23c494"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(1882),
                            EndDate = new DateTime(2021, 9, 3, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(1577),
                            EventDescription = " Pouros, Erdman and Bailey 's 64 rd/th Annual Conference at United States Minor Outlying Islands, South Quincyfort - INTEGRATED SECONDARY KNOWLEDGE BASE. ",
                            EventName = " Pouros, Erdman and Bailey 's 64 rd/th Annual Conference",
                            EventTimezone = "Australia/Broken_Hill",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(1884),
                            StartDate = new DateTime(2021, 9, 2, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(1577)
                        },
                        new
                        {
                            Identifier = new Guid("bac1fbdd-3a54-47b2-bb06-42c49f175819"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(4601),
                            EndDate = new DateTime(2021, 9, 18, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(4491),
                            EventDescription = " Dooley, Conn and Wiza 's 79 rd/th Annual Conference at Saudi Arabia, Durganmouth - ORGANIC INTANGIBLE WEBSITE. ",
                            EventName = " Dooley, Conn and Wiza 's 79 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(4604),
                            StartDate = new DateTime(2021, 9, 17, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(4491)
                        },
                        new
                        {
                            Identifier = new Guid("7c47d40c-6ce5-40f9-811d-0a1840d4109f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(7586),
                            EndDate = new DateTime(2021, 7, 14, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(7547),
                            EventDescription = " Dickens Inc and Sons 's 13 rd/th Annual Conference at Ethiopia, South Mathew - MULTI-LAYERED ASSYMETRIC DATA-WAREHOUSE. ",
                            EventName = " Dickens Inc and Sons 's 13 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(7588),
                            StartDate = new DateTime(2021, 7, 13, 0, 2, 22, 490, DateTimeKind.Local).AddTicks(7547)
                        },
                        new
                        {
                            Identifier = new Guid("b1782ec6-f3bd-4da8-8063-cb35090a8b3d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(106),
                            EndDate = new DateTime(2021, 10, 4, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(84),
                            EventDescription = " Donnelly-Zemlak 's 95 rd/th Annual Conference at French Guiana, North Waldoberg - PROACTIVE BACKGROUND INSTALLATION. ",
                            EventName = " Donnelly-Zemlak 's 95 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(108),
                            StartDate = new DateTime(2021, 10, 3, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(84)
                        },
                        new
                        {
                            Identifier = new Guid("5870a3ff-0bad-4442-8e05-3c208ce53723"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(2426),
                            EndDate = new DateTime(2021, 9, 25, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(2405),
                            EventDescription = " Berge LLC 's 86 rd/th Annual Conference at Cote d'Ivoire, New Alishaberg - UPGRADABLE DISCRETE MIDDLEWARE. ",
                            EventName = " Berge LLC 's 86 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(2427),
                            StartDate = new DateTime(2021, 9, 24, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(2405)
                        },
                        new
                        {
                            Identifier = new Guid("bc98602a-713f-4b0e-80b3-326a06a5d189"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(4305),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(4276),
                            EventDescription = " Champlin-Mohr 's 12 rd/th Annual Conference at French Southern Territories, Waterston - ADVANCED DISCRETE PRODUCTIVITY. ",
                            EventName = " Champlin-Mohr 's 12 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(4306),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(4276)
                        },
                        new
                        {
                            Identifier = new Guid("37e9fda9-844d-4519-912f-0bbe9e040867"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(6793),
                            EndDate = new DateTime(2021, 7, 28, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(6773),
                            EventDescription = " Kassulke-Armstrong 's 27 rd/th Annual Conference at Kiribati, North Mario - CUSTOMIZABLE FRESH-THINKING CAPACITY. ",
                            EventName = " Kassulke-Armstrong 's 27 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(6795),
                            StartDate = new DateTime(2021, 7, 27, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(6773)
                        },
                        new
                        {
                            Identifier = new Guid("3d69273f-709c-495a-9d43-71298aa1b0fa"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(9298),
                            EndDate = new DateTime(2021, 7, 27, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(9278),
                            EventDescription = " Will LLC 's 26 rd/th Annual Conference at Argentina, Kendrickside - IMPLEMENTED NATIONAL ALGORITHM. ",
                            EventName = " Will LLC 's 26 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(9299),
                            StartDate = new DateTime(2021, 7, 26, 0, 2, 22, 491, DateTimeKind.Local).AddTicks(9278)
                        },
                        new
                        {
                            Identifier = new Guid("2be7f9e4-6c23-4339-988f-780b6f51d5fd"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(656),
                            EndDate = new DateTime(2021, 9, 23, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(636),
                            EventDescription = " Hand-Hermann 's 84 rd/th Annual Conference at Mayotte, Stantonfort - EXTENDED CONTEXT-SENSITIVE THROUGHPUT. ",
                            EventName = " Hand-Hermann 's 84 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(657),
                            StartDate = new DateTime(2021, 9, 22, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(636)
                        },
                        new
                        {
                            Identifier = new Guid("dd5f9eee-66c5-4eac-b3d8-8d711021abc4"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(1761),
                            EndDate = new DateTime(2021, 7, 27, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(1739),
                            EventDescription = " Roob LLC 's 26 rd/th Annual Conference at Dominica, Kuhicchester - INTEGRATED RADICAL FORECAST. ",
                            EventName = " Roob LLC 's 26 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(1762),
                            StartDate = new DateTime(2021, 7, 26, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(1739)
                        },
                        new
                        {
                            Identifier = new Guid("bb7d240e-4842-4f6b-816b-424a4e5e1c22"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(3236),
                            EndDate = new DateTime(2021, 9, 19, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(3193),
                            EventDescription = " Bailey-Green 's 80 rd/th Annual Conference at Qatar, Smithstad - IMPLEMENTED SYSTEMIC CHALLENGE. ",
                            EventName = " Bailey-Green 's 80 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(3237),
                            StartDate = new DateTime(2021, 9, 18, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(3193)
                        },
                        new
                        {
                            Identifier = new Guid("5d67769b-3942-42d8-8097-fb3bc3dd8b00"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(7586),
                            EndDate = new DateTime(2021, 7, 18, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(7538),
                            EventDescription = " Breitenberg, Cremin and Maggio 's 17 rd/th Annual Conference at Germany, North Ellieberg - FUNCTION-BASED 24/7 UTILISATION. ",
                            EventName = " Breitenberg, Cremin and Maggio 's 17 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(7587),
                            StartDate = new DateTime(2021, 7, 17, 0, 2, 22, 492, DateTimeKind.Local).AddTicks(7538)
                        },
                        new
                        {
                            Identifier = new Guid("6d876f83-4170-4ad6-af70-1e558546c6f2"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(200),
                            EndDate = new DateTime(2021, 9, 5, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(179),
                            EventDescription = " Dibbert-Hansen 's 66 rd/th Annual Conference at Central African Republic, West Dewittmouth - ENHANCED WELL-MODULATED KNOWLEDGE BASE. ",
                            EventName = " Dibbert-Hansen 's 66 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(202),
                            StartDate = new DateTime(2021, 9, 4, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(179)
                        },
                        new
                        {
                            Identifier = new Guid("2d041855-14c1-4a74-922f-a739fb3b56b0"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(1710),
                            EndDate = new DateTime(2021, 8, 10, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(1684),
                            EventDescription = " Herman-Hauck 's 40 rd/th Annual Conference at Honduras, Wehnerburgh - ORGANIC SOLUTION-ORIENTED FLEXIBILITY. ",
                            EventName = " Herman-Hauck 's 40 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(1711),
                            StartDate = new DateTime(2021, 8, 9, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(1684)
                        },
                        new
                        {
                            Identifier = new Guid("32018a69-d3bf-468f-8662-16a8110d168f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(4650),
                            EndDate = new DateTime(2021, 7, 7, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(4629),
                            EventDescription = " Hammes-Roob 's 6 rd/th Annual Conference at Marshall Islands, North Emiliastad - DOWN-SIZED FAULT-TOLERANT GROUPWARE. ",
                            EventName = " Hammes-Roob 's 6 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(4651),
                            StartDate = new DateTime(2021, 7, 6, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(4629)
                        },
                        new
                        {
                            Identifier = new Guid("141896ba-cb0b-4276-86e2-d807636bce65"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(5764),
                            EndDate = new DateTime(2021, 9, 8, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(5745),
                            EventDescription = " Leannon Group 's 69 rd/th Annual Conference at Brunei Darussalam, Dibberttown - ENTERPRISE-WIDE NEUTRAL MODERATOR. ",
                            EventName = " Leannon Group 's 69 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(5765),
                            StartDate = new DateTime(2021, 9, 7, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            Identifier = new Guid("618f5bda-dbf1-41b6-b8b3-f0dd02a61326"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(8573),
                            EndDate = new DateTime(2021, 9, 29, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(8547),
                            EventDescription = " Cummerata, Barton and Smitham 's 90 rd/th Annual Conference at Bhutan, Rowanville - CONFIGURABLE GLOBAL UTILISATION. ",
                            EventName = " Cummerata, Barton and Smitham 's 90 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(8574),
                            StartDate = new DateTime(2021, 9, 28, 0, 2, 22, 493, DateTimeKind.Local).AddTicks(8547)
                        },
                        new
                        {
                            Identifier = new Guid("cd9ec2b0-0b04-4451-84de-6b289f8f2846"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(958),
                            EndDate = new DateTime(2021, 10, 8, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(935),
                            EventDescription = " Will Inc and Sons 's 99 rd/th Annual Conference at Latvia, Port Tyrelburgh - QUALITY-FOCUSED REAL-TIME GRAPHICAL USER INTERFACE. ",
                            EventName = " Will Inc and Sons 's 99 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(959),
                            StartDate = new DateTime(2021, 10, 7, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(935)
                        },
                        new
                        {
                            Identifier = new Guid("74c4ca4b-ab6d-4a9a-bbef-11f9e915ae21"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(3732),
                            EndDate = new DateTime(2021, 8, 13, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(3710),
                            EventDescription = " Cormier, Conn and Shields 's 43 rd/th Annual Conference at Uruguay, Rafaelfurt - CONFIGURABLE STATIC EMULATION. ",
                            EventName = " Cormier, Conn and Shields 's 43 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(3733),
                            StartDate = new DateTime(2021, 8, 12, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(3710)
                        },
                        new
                        {
                            Identifier = new Guid("484ba87e-7d08-4294-bc18-02619b74eea6"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(6670),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(6643),
                            EventDescription = " Luettgen, Streich and McGlynn 's 12 rd/th Annual Conference at Nigeria, Gracieland - PUBLIC-KEY CONTEXTUALLY-BASED PROCESS IMPROVEMENT. ",
                            EventName = " Luettgen, Streich and McGlynn 's 12 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(6672),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 494, DateTimeKind.Local).AddTicks(6643)
                        },
                        new
                        {
                            Identifier = new Guid("b158df44-1812-4c86-97ac-49de85f6d310"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(651),
                            EndDate = new DateTime(2021, 8, 21, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(550),
                            EventDescription = " Abshire-Morissette 's 51 rd/th Annual Conference at Cyprus, New Jairo - PROGRESSIVE MULTI-TASKING ORCHESTRATION. ",
                            EventName = " Abshire-Morissette 's 51 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(652),
                            StartDate = new DateTime(2021, 8, 20, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(550)
                        },
                        new
                        {
                            Identifier = new Guid("2283f043-1024-4230-994e-50aac9e7901f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(3650),
                            EndDate = new DateTime(2021, 7, 29, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(3618),
                            EventDescription = " Grimes-Predovic 's 28 rd/th Annual Conference at Greece, North Vicentachester - CENTRALIZED COMPOSITE FUNCTIONALITIES. ",
                            EventName = " Grimes-Predovic 's 28 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(3652),
                            StartDate = new DateTime(2021, 7, 28, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(3618)
                        },
                        new
                        {
                            Identifier = new Guid("5e4e7974-352e-4243-af20-e6b09c91da91"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(7629),
                            EndDate = new DateTime(2021, 7, 12, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(7417),
                            EventDescription = " Stroman Group 's 11 rd/th Annual Conference at Finland, Port Gage - CLONED HEURISTIC ADAPTER. ",
                            EventName = " Stroman Group 's 11 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(7631),
                            StartDate = new DateTime(2021, 7, 11, 0, 2, 22, 495, DateTimeKind.Local).AddTicks(7417)
                        },
                        new
                        {
                            Identifier = new Guid("5c5be19e-6952-4dcd-8fa4-356860f39fd3"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(1972),
                            EndDate = new DateTime(2021, 7, 5, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(1840),
                            EventDescription = " Kihn, Olson and Gutmann 's 4 rd/th Annual Conference at Jamaica, Lake Rebekahburgh - DIGITIZED DEDICATED OPEN SYSTEM. ",
                            EventName = " Kihn, Olson and Gutmann 's 4 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(1975),
                            StartDate = new DateTime(2021, 7, 4, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(1840)
                        },
                        new
                        {
                            Identifier = new Guid("a278c8c2-37cd-4568-8096-9a44962fdbd1"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(5566),
                            EndDate = new DateTime(2021, 8, 29, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(5470),
                            EventDescription = " Schneider Inc and Sons 's 59 rd/th Annual Conference at Italy, New Clemmie - CROSS-PLATFORM DIRECTIONAL PRICING STRUCTURE. ",
                            EventName = " Schneider Inc and Sons 's 59 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(5568),
                            StartDate = new DateTime(2021, 8, 28, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(5470)
                        },
                        new
                        {
                            Identifier = new Guid("f5af59db-793c-429d-8f56-4f03f89b894d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(9258),
                            EndDate = new DateTime(2021, 8, 8, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(9170),
                            EventDescription = " Schaden-Pacocha 's 38 rd/th Annual Conference at Colombia, East Sofiaburgh - ENHANCED MULTI-TASKING ENCRYPTION. ",
                            EventName = " Schaden-Pacocha 's 38 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(9260),
                            StartDate = new DateTime(2021, 8, 7, 0, 2, 22, 496, DateTimeKind.Local).AddTicks(9170)
                        },
                        new
                        {
                            Identifier = new Guid("8fc33285-1e68-4b67-95dc-1e5006f68624"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(1500),
                            EndDate = new DateTime(2021, 9, 2, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(1406),
                            EventDescription = " Leffler LLC 's 63 rd/th Annual Conference at Seychelles, Morissetteburgh - OBJECT-BASED MULTI-TASKING PROJECTION. ",
                            EventName = " Leffler LLC 's 63 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(1502),
                            StartDate = new DateTime(2021, 9, 1, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(1406)
                        },
                        new
                        {
                            Identifier = new Guid("c62b0538-c3c9-4a49-91d1-104a2eb0be29"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(4757),
                            EndDate = new DateTime(2021, 7, 9, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(4718),
                            EventDescription = " McCullough Inc and Sons 's 8 rd/th Annual Conference at Sri Lanka, Carolinaside - STAND-ALONE ACTUATING ORCHESTRATION. ",
                            EventName = " McCullough Inc and Sons 's 8 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(4759),
                            StartDate = new DateTime(2021, 7, 8, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(4718)
                        },
                        new
                        {
                            Identifier = new Guid("c277c01a-833f-473f-a881-e1af8d1a7c49"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(8218),
                            EndDate = new DateTime(2021, 7, 16, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(8164),
                            EventDescription = " Dach Group 's 15 rd/th Annual Conference at Sierra Leone, West Ivah - OBJECT-BASED METHODICAL PROTOCOL. ",
                            EventName = " Dach Group 's 15 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(8219),
                            StartDate = new DateTime(2021, 7, 15, 0, 2, 22, 497, DateTimeKind.Local).AddTicks(8164)
                        },
                        new
                        {
                            Identifier = new Guid("ea7861d4-5eff-44ac-8c23-65127d7219a5"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(2059),
                            EndDate = new DateTime(2021, 7, 10, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(2019),
                            EventDescription = " Hamill-Hermiston 's 9 rd/th Annual Conference at Bulgaria, Port Myrticeshire - CONFIGURABLE BACKGROUND ABILITY. ",
                            EventName = " Hamill-Hermiston 's 9 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(2061),
                            StartDate = new DateTime(2021, 7, 9, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(2019)
                        },
                        new
                        {
                            Identifier = new Guid("cd7a35a3-72ee-4a39-9ea3-b1992964a962"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(5713),
                            EndDate = new DateTime(2021, 9, 10, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(5667),
                            EventDescription = " Kozey-Labadie 's 71 rd/th Annual Conference at Holy See (Vatican City State), Kellybury - MULTI-CHANNELLED HIGH-LEVEL OPEN ARCHITECTURE. ",
                            EventName = " Kozey-Labadie 's 71 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(5715),
                            StartDate = new DateTime(2021, 9, 9, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(5667)
                        },
                        new
                        {
                            Identifier = new Guid("19054af0-d609-448b-9ac6-073787d5ee78"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(9551),
                            EndDate = new DateTime(2021, 9, 3, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(9507),
                            EventDescription = " Anderson-Gulgowski 's 64 rd/th Annual Conference at Grenada, South Cobyberg - COMPATIBLE DEDICATED HARDWARE. ",
                            EventName = " Anderson-Gulgowski 's 64 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(9553),
                            StartDate = new DateTime(2021, 9, 2, 0, 2, 22, 498, DateTimeKind.Local).AddTicks(9507)
                        },
                        new
                        {
                            Identifier = new Guid("653343f7-00b8-44a4-b399-1923ebfc701b"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(3557),
                            EndDate = new DateTime(2021, 9, 16, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(3519),
                            EventDescription = " Dicki-Witting 's 77 rd/th Annual Conference at Belize, Port Cassandreburgh - COMPATIBLE 4TH GENERATION SUCCESS. ",
                            EventName = " Dicki-Witting 's 77 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(3559),
                            StartDate = new DateTime(2021, 9, 15, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(3519)
                        },
                        new
                        {
                            Identifier = new Guid("cad203d2-c64f-4fd0-bca5-78028ba2bb07"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(6944),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(6895),
                            EventDescription = " Friesen Group 's 12 rd/th Annual Conference at Netherlands, New Laviniaport - RE-CONTEXTUALIZED SYSTEMIC HELP-DESK. ",
                            EventName = " Friesen Group 's 12 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(6946),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 499, DateTimeKind.Local).AddTicks(6895)
                        },
                        new
                        {
                            Identifier = new Guid("75e97b1b-2630-4960-a4f1-d5b62bb416ba"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(697),
                            EndDate = new DateTime(2021, 7, 6, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(648),
                            EventDescription = " Schneider-Klein 's 5 rd/th Annual Conference at Namibia, North Maymiestad - VERSATILE EXPLICIT GRAPHICAL USER INTERFACE. ",
                            EventName = " Schneider-Klein 's 5 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(699),
                            StartDate = new DateTime(2021, 7, 5, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(648)
                        },
                        new
                        {
                            Identifier = new Guid("44458ed9-315b-43b8-89c1-ed37d95fb90c"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(4881),
                            EndDate = new DateTime(2021, 8, 12, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(4823),
                            EventDescription = " McLaughlin, Heidenreich and Homenick 's 42 rd/th Annual Conference at Vietnam, West Tyshawn - MULTI-LAYERED VALUE-ADDED DEFINITION. ",
                            EventName = " McLaughlin, Heidenreich and Homenick 's 42 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(4883),
                            StartDate = new DateTime(2021, 8, 11, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(4823)
                        },
                        new
                        {
                            Identifier = new Guid("cf95283b-9c81-41e1-917a-995844c1162b"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(8974),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(8907),
                            EventDescription = " DuBuque, Glover and Turner 's 12 rd/th Annual Conference at Germany, Isacshire - HORIZONTAL EXECUTIVE SERVICE-DESK. ",
                            EventName = " DuBuque, Glover and Turner 's 12 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(8976),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 500, DateTimeKind.Local).AddTicks(8907)
                        },
                        new
                        {
                            Identifier = new Guid("754165a7-7ba7-470c-9b4b-db0f835152e5"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(3304),
                            EndDate = new DateTime(2021, 9, 21, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(3237),
                            EventDescription = " Fisher, Kuhn and Bartoletti 's 82 rd/th Annual Conference at Tajikistan, Diamondchester - UPGRADABLE 24 HOUR CAPABILITY. ",
                            EventName = " Fisher, Kuhn and Bartoletti 's 82 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(3307),
                            StartDate = new DateTime(2021, 9, 20, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(3237)
                        },
                        new
                        {
                            Identifier = new Guid("936c7aad-5307-4294-9ab6-7f01e94c2c96"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(5153),
                            EndDate = new DateTime(2021, 9, 27, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(5083),
                            EventDescription = " Feil Inc and Sons 's 88 rd/th Annual Conference at Canada, Daughertyland - CLONED DEDICATED INITIATIVE. ",
                            EventName = " Feil Inc and Sons 's 88 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(5156),
                            StartDate = new DateTime(2021, 9, 26, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            Identifier = new Guid("c0bb7af9-e360-49d1-8f67-da2a0ffff2cd"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(8984),
                            EndDate = new DateTime(2021, 7, 8, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(8871),
                            EventDescription = " Torphy Group 's 7 rd/th Annual Conference at Israel, East Jon - TRIPLE-BUFFERED BOTTOM-LINE KNOWLEDGE USER. ",
                            EventName = " Torphy Group 's 7 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(8986),
                            StartDate = new DateTime(2021, 7, 7, 0, 2, 22, 501, DateTimeKind.Local).AddTicks(8871)
                        },
                        new
                        {
                            Identifier = new Guid("a10fc04b-573f-439a-b71e-c1fccc0ebd26"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(2726),
                            EndDate = new DateTime(2021, 8, 15, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(2678),
                            EventDescription = " Bernier-Rempel 's 45 rd/th Annual Conference at Comoros, Port Clotilde - CROSS-PLATFORM LEADING EDGE HIERARCHY. ",
                            EventName = " Bernier-Rempel 's 45 rd/th Annual Conference",
                            EventTimezone = "Australia/Brisbane",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(2727),
                            StartDate = new DateTime(2021, 8, 14, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(2678)
                        },
                        new
                        {
                            Identifier = new Guid("21c9c588-cdd9-4d73-a952-4bcb362ea72a"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(6805),
                            EndDate = new DateTime(2021, 7, 22, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(6759),
                            EventDescription = " Doyle, Kuvalis and O'Kon 's 21 rd/th Annual Conference at Gambia, Lavadamouth - CUSTOMIZABLE WELL-MODULATED SERVICE-DESK. ",
                            EventName = " Doyle, Kuvalis and O'Kon 's 21 rd/th Annual Conference",
                            EventTimezone = "Antarctica/Macquarie",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(6807),
                            StartDate = new DateTime(2021, 7, 21, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Identifier = new Guid("15ce556d-aa95-4491-aa08-b79d109c66f5"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(32),
                            EndDate = new DateTime(2021, 8, 4, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(9992),
                            EventDescription = " Moen Group 's 34 rd/th Annual Conference at New Caledonia, Lake Jaycee - CENTRALIZED MULTIMEDIA ORCHESTRATION. ",
                            EventName = " Moen Group 's 34 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(34),
                            StartDate = new DateTime(2021, 8, 3, 0, 2, 22, 502, DateTimeKind.Local).AddTicks(9992)
                        },
                        new
                        {
                            Identifier = new Guid("bd7f5163-9e38-4492-b3f5-d43371a25034"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(4138),
                            EndDate = new DateTime(2021, 8, 15, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(4090),
                            EventDescription = " Padberg, Howell and Gulgowski 's 45 rd/th Annual Conference at Cyprus, Leannabury - REALIGNED INTERMEDIATE BENCHMARK. ",
                            EventName = " Padberg, Howell and Gulgowski 's 45 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(4140),
                            StartDate = new DateTime(2021, 8, 14, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(4090)
                        },
                        new
                        {
                            Identifier = new Guid("d872bf3e-1d89-4192-b45e-8ffa478acfbc"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(7886),
                            EndDate = new DateTime(2021, 9, 24, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(7827),
                            EventDescription = " Jast-Willms 's 85 rd/th Annual Conference at Indonesia, South Dasia - CENTRALIZED SYSTEMATIC BENCHMARK. ",
                            EventName = " Jast-Willms 's 85 rd/th Annual Conference",
                            EventTimezone = "Australia/Broken_Hill",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(7888),
                            StartDate = new DateTime(2021, 9, 23, 0, 2, 22, 503, DateTimeKind.Local).AddTicks(7827)
                        },
                        new
                        {
                            Identifier = new Guid("c93367ae-7783-45da-aabb-011602374510"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(1910),
                            EndDate = new DateTime(2021, 8, 12, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(1861),
                            EventDescription = " Champlin-Quitzon 's 42 rd/th Annual Conference at Algeria, East Jeraldchester - DIVERSE EXECUTIVE APPLICATION. ",
                            EventName = " Champlin-Quitzon 's 42 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(1911),
                            StartDate = new DateTime(2021, 8, 11, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(1861)
                        },
                        new
                        {
                            Identifier = new Guid("7aceb22c-c792-4165-9437-77abc5029941"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(5742),
                            EndDate = new DateTime(2021, 8, 15, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(5695),
                            EventDescription = " Koepp, Fay and Gislason 's 45 rd/th Annual Conference at Nepal, Jarvistown - SEAMLESS STATIC FIRMWARE. ",
                            EventName = " Koepp, Fay and Gislason 's 45 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(5743),
                            StartDate = new DateTime(2021, 8, 14, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(5695)
                        },
                        new
                        {
                            Identifier = new Guid("1ff9d872-2812-4bb3-b16e-015a61d7b842"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(9521),
                            EndDate = new DateTime(2021, 9, 5, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(9473),
                            EventDescription = " Fay-Little 's 66 rd/th Annual Conference at Guyana, South Briannehaven - REDUCED EXPLICIT SUCCESS. ",
                            EventName = " Fay-Little 's 66 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(9523),
                            StartDate = new DateTime(2021, 9, 4, 0, 2, 22, 504, DateTimeKind.Local).AddTicks(9473)
                        },
                        new
                        {
                            Identifier = new Guid("caf8bd9e-cbbf-4469-bfe7-fa6550e202f7"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(3288),
                            EndDate = new DateTime(2021, 8, 28, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(3240),
                            EventDescription = " Nicolas Inc and Sons 's 58 rd/th Annual Conference at Nicaragua, West Niashire - INTEGRATED 24/7 ABILITY. ",
                            EventName = " Nicolas Inc and Sons 's 58 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(3289),
                            StartDate = new DateTime(2021, 8, 27, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(3240)
                        },
                        new
                        {
                            Identifier = new Guid("6feeb07a-2800-411c-8acd-becc99535e0e"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(7574),
                            EndDate = new DateTime(2021, 7, 24, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(7525),
                            EventDescription = " Sanford-Hills 's 23 rd/th Annual Conference at Paraguay, West Jennyfer - MULTI-LAYERED TERTIARY DATA-WAREHOUSE. ",
                            EventName = " Sanford-Hills 's 23 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(7576),
                            StartDate = new DateTime(2021, 7, 23, 0, 2, 22, 505, DateTimeKind.Local).AddTicks(7525)
                        },
                        new
                        {
                            Identifier = new Guid("34e277dc-caa0-43af-b3a8-280e04d8b55a"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(1275),
                            EndDate = new DateTime(2021, 9, 22, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(1225),
                            EventDescription = " Larson Inc and Sons 's 83 rd/th Annual Conference at Mauritius, North Evahaven - AUTOMATED GLOBAL SOFTWARE. ",
                            EventName = " Larson Inc and Sons 's 83 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(1276),
                            StartDate = new DateTime(2021, 9, 21, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(1225)
                        },
                        new
                        {
                            Identifier = new Guid("a10db101-6c5c-4fcc-9803-4b5ce317f44a"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(3364),
                            EndDate = new DateTime(2021, 7, 15, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(3314),
                            EventDescription = " Wolff-Runolfsson 's 14 rd/th Annual Conference at Panama, Emardmouth - ORGANIZED SYSTEM-WORTHY CAPABILITY. ",
                            EventName = " Wolff-Runolfsson 's 14 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(3366),
                            StartDate = new DateTime(2021, 7, 14, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(3314)
                        },
                        new
                        {
                            Identifier = new Guid("0996c8ef-1e05-4173-aea7-723662736cf5"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(7423),
                            EndDate = new DateTime(2021, 8, 21, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(7249),
                            EventDescription = " Boyer LLC 's 51 rd/th Annual Conference at Timor-Leste, West Garretfort - SHARABLE ZERO ADMINISTRATION SECURED LINE. ",
                            EventName = " Boyer LLC 's 51 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(7426),
                            StartDate = new DateTime(2021, 8, 20, 0, 2, 22, 506, DateTimeKind.Local).AddTicks(7249)
                        },
                        new
                        {
                            Identifier = new Guid("950104e4-235c-4bd4-b94d-2a1e88af13bf"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(1796),
                            EndDate = new DateTime(2021, 8, 10, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(1737),
                            EventDescription = " Walker LLC 's 40 rd/th Annual Conference at Turks and Caicos Islands, Port Tressaborough - ORGANIC MULTI-STATE GROUPWARE. ",
                            EventName = " Walker LLC 's 40 rd/th Annual Conference",
                            EventTimezone = "Australia/Hobart",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(1799),
                            StartDate = new DateTime(2021, 8, 9, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(1737)
                        },
                        new
                        {
                            Identifier = new Guid("d7839527-eed7-45e5-aadf-7623f820e501"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(6712),
                            EndDate = new DateTime(2021, 9, 17, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(6630),
                            EventDescription = " Bayer, Murray and Gaylord 's 78 rd/th Annual Conference at Haiti, Lake Andy - CROSS-GROUP ZERO TOLERANCE SOFTWARE. ",
                            EventName = " Bayer, Murray and Gaylord 's 78 rd/th Annual Conference",
                            EventTimezone = "Australia/Lord_Howe",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(6715),
                            StartDate = new DateTime(2021, 9, 16, 0, 2, 22, 507, DateTimeKind.Local).AddTicks(6630)
                        },
                        new
                        {
                            Identifier = new Guid("b4c22875-7af1-4aa1-ad06-20f837c43b7c"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 508, DateTimeKind.Local).AddTicks(413),
                            EndDate = new DateTime(2021, 10, 3, 0, 2, 22, 508, DateTimeKind.Local).AddTicks(361),
                            EventDescription = " Koepp Inc and Sons 's 94 rd/th Annual Conference at Gabon, Candaceton - FACE TO FACE NEXT GENERATION ENCODING. ",
                            EventName = " Koepp Inc and Sons 's 94 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 508, DateTimeKind.Local).AddTicks(416),
                            StartDate = new DateTime(2021, 10, 2, 0, 2, 22, 508, DateTimeKind.Local).AddTicks(361)
                        },
                        new
                        {
                            Identifier = new Guid("4afc354b-0f4d-42a4-9096-87a6f24c1fa1"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(4602),
                            EndDate = new DateTime(2021, 9, 4, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(4140),
                            EventDescription = " Dare, Johnson and Dibbert 's 65 rd/th Annual Conference at Kyrgyz Republic, North Cathrine - FUNCTION-BASED HEURISTIC FLEXIBILITY. ",
                            EventName = " Dare, Johnson and Dibbert 's 65 rd/th Annual Conference",
                            EventTimezone = "Australia/Darwin",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(4606),
                            StartDate = new DateTime(2021, 9, 3, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(4140)
                        },
                        new
                        {
                            Identifier = new Guid("306fca66-a05b-4bc8-b35c-9fae3dce3051"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(7864),
                            EndDate = new DateTime(2021, 8, 26, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(7787),
                            EventDescription = " Kirlin-Wintheiser 's 56 rd/th Annual Conference at Greenland, Port Reynoldside - ERGONOMIC WEB-ENABLED INFO-MEDIARIES. ",
                            EventName = " Kirlin-Wintheiser 's 56 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(7867),
                            StartDate = new DateTime(2021, 8, 25, 0, 2, 22, 532, DateTimeKind.Local).AddTicks(7787)
                        },
                        new
                        {
                            Identifier = new Guid("d84d1c5e-71ea-42c6-8bf5-124f2f1f863f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(408),
                            EndDate = new DateTime(2021, 7, 26, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(373),
                            EventDescription = " Gerhold LLC 's 25 rd/th Annual Conference at Lebanon, Lake Nicostad - QUALITY-FOCUSED COHERENT ENCODING. ",
                            EventName = " Gerhold LLC 's 25 rd/th Annual Conference",
                            EventTimezone = "Australia/Sydney",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(411),
                            StartDate = new DateTime(2021, 7, 25, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(373)
                        },
                        new
                        {
                            Identifier = new Guid("19a3a122-d4aa-4975-8307-d651fe891b5d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(3101),
                            EndDate = new DateTime(2021, 9, 2, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(3063),
                            EventDescription = " Rodriguez-Schuster 's 63 rd/th Annual Conference at Myanmar, Briannetown - REVERSE-ENGINEERED 6TH GENERATION OPEN SYSTEM. ",
                            EventName = " Rodriguez-Schuster 's 63 rd/th Annual Conference",
                            EventTimezone = "Australia/Eucla",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(3104),
                            StartDate = new DateTime(2021, 9, 1, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(3063)
                        },
                        new
                        {
                            Identifier = new Guid("bd7d3606-da5c-414f-b5dc-198e7b46309d"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(5799),
                            EndDate = new DateTime(2021, 10, 3, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(5763),
                            EventDescription = " Hessel-Beatty 's 94 rd/th Annual Conference at Pitcairn Islands, East Uriah - CLONED CONTEXTUALLY-BASED HARDWARE. ",
                            EventName = " Hessel-Beatty 's 94 rd/th Annual Conference",
                            EventTimezone = "Australia/Melbourne",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(5802),
                            StartDate = new DateTime(2021, 10, 2, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(5763)
                        },
                        new
                        {
                            Identifier = new Guid("db51f650-e884-458a-a6d2-38f9b3948757"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(7852),
                            EndDate = new DateTime(2021, 8, 23, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(7807),
                            EventDescription = " Dooley, Mayer and Kessler 's 53 rd/th Annual Conference at United States Minor Outlying Islands, Gaylordfurt - MULTI-LATERAL HUMAN-RESOURCE FUNCTION. ",
                            EventName = " Dooley, Mayer and Kessler 's 53 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(7855),
                            StartDate = new DateTime(2021, 8, 22, 0, 2, 22, 533, DateTimeKind.Local).AddTicks(7807)
                        },
                        new
                        {
                            Identifier = new Guid("11f896cf-2570-47b6-b4d4-25e3b6f836bc"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(464),
                            EndDate = new DateTime(2021, 7, 13, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(424),
                            EventDescription = " Hodkiewicz-Harvey 's 12 rd/th Annual Conference at Belarus, Port Keegan - OPEN-ARCHITECTED INTERMEDIATE MONITORING. ",
                            EventName = " Hodkiewicz-Harvey 's 12 rd/th Annual Conference",
                            EventTimezone = "Australia/Adelaide",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(466),
                            StartDate = new DateTime(2021, 7, 12, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(424)
                        },
                        new
                        {
                            Identifier = new Guid("589ab285-a61d-4e24-8479-5e950a5bb3d8"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(3327),
                            EndDate = new DateTime(2021, 9, 9, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(3252),
                            EventDescription = " Frami, Wisozk and Heathcote 's 70 rd/th Annual Conference at Saudi Arabia, North Tavares - FACE TO FACE REGIONAL FRAMEWORK. ",
                            EventName = " Frami, Wisozk and Heathcote 's 70 rd/th Annual Conference",
                            EventTimezone = "Australia/Lindeman",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(3328),
                            StartDate = new DateTime(2021, 9, 8, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(3252)
                        },
                        new
                        {
                            Identifier = new Guid("7875d893-786c-44d9-9ff1-3fcb2b16ec6f"),
                            CreatedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(6176),
                            EndDate = new DateTime(2021, 8, 28, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(6121),
                            EventDescription = " Cormier, Kessler and King 's 58 rd/th Annual Conference at Korea, Port Viviennestad - SHARABLE STATIC METHODOLOGY. ",
                            EventName = " Cormier, Kessler and King 's 58 rd/th Annual Conference",
                            EventTimezone = "Australia/Perth",
                            ModifiedDate = new DateTime(2021, 6, 30, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(6178),
                            StartDate = new DateTime(2021, 8, 27, 0, 2, 22, 534, DateTimeKind.Local).AddTicks(6121)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
